### ISSUE TITLE
Accelerate Updated to 2.0

### ISSUE THREAD

**Issue by noeltock** [pantheon-systems/hw2022-pantheon-dxp#59]
Hey @jazzsequence , hope you're well 🎉 

Just an FYI that we've rebuilt a lot of the UI/UX inside of Accelerate, you can watch some videos here:
https://www.linkedin.com/feed/update/urn:li:activity:7031164757957120000/
https://www.linkedin.com/feed/update/urn:li:activity:7031469254340222977/

WP-org has been updated with latest too. Let me know if you ever want to jump on where I can help... feel free to close once seen 🚀 

Cheers,
Noel

**Comment by jazzsequence** [comment]
Hey, thanks for the wave @noeltock 👋 
Definitely interested in checking those out. :)
